# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:
- task: GoTool@0
  inputs:
    version: '1.20.2'
- task: ShellScript@2
  inputs:
    scriptPath: data/integration/run-integration.sh
    cwd: ./data
- task: Go@0
  inputs:
    command: 'test'
    arguments: '-tags fts5 -v ./...'
    workingDirectory: './data'
- task: Go@0
  inputs:
    command: 'test'
    arguments: ' -v ./...'
    workingDirectory: './web'
