version: '3.3'
services:
  database:
    image: mariadb:latest
    ports:
      - 3366:3306
    volumes:
      - flibudata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=${ENV_MARIADB_PASSWORD}
      - MYSQL_USER=${ENV_MARIADB_USER}
      - MYSQL_DATABASE=${ENV_MARIADB_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${ENV_MARIADB_USER}", "-p${ENV_MARIADB_PASSWORD}"]
      interval: 30s
      timeout: 30s
      retries: 99999

  flibuserver:
    build:
      context: ./data
    links:
      - database
    environment:
      MARIADB_HOST: ${ENV_MARIADB_HOST}
      MARIADB_USER: ${ENV_MARIADB_USER}
      MARIADB_PASSWORD: ${ENV_MARIADB_PASSWORD}
      MARIADB_DATABASE: ${ENV_MARIADB_DATABASE}
      MARIADB_PORT: 3306
      TELEGRAM_API_KEY: ${ENV_TELEGRAM_API_KEY}
      TELEGRAM_CHAT_ID: ${ENV_TELEGRAM_CHAT_ID}
      FLIBUSTA_BASE_URL: ${ENV_FLIBUSTA_BASE_URL}
      FLIBUSERVER_PORT: ${ENV_FLIBUSERVER_PORT}
    depends_on:
      - database
    volumes:
      - 'flibudata:/var/local/flibudata'
    ports:
      - '${ENV_FLIBUSERVER_PORT}:${ENV_FLIBUSERVER_PORT}'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./grpc_health_probe-linux-amd64", "-addr=localhost:${ENV_FLIBUSERVER_PORT}"]
      interval: 30s
      timeout: 30s
      retries: 99999
  web:
    build:
      context: ./web
    environment:
      TELEGRAM_API_KEY: ${ENV_TELEGRAM_API_KEY}
      BACKEND_URL: flibuserver:${ENV_FLIBUSERVER_PORT}
      WEB_PORT: ${ENV_FLIBUWEB_PORT}
      BOT_NAME: ${ENV_BOT_NAME}
      DOMAIN_NAME: ${ENV_DOMAIN_NAME}
    depends_on:
      flibuserver:
        condition: service_healthy
    ports:
      - '${ENV_FLIBUWEB_PORT}:${ENV_FLIBUWEB_PORT}'
volumes:
  flibudata: